name: 'CI: verify build'

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          service_account: 'websight-dxp-gh-actions@websight-dxp-development.iam.gserviceaccount.com'
          credentials_json: ${{ secrets.GCP_SERVICE_CREDENTIALS_JSON }}
          token_format: access_token
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - uses: actions/cache@v3
      - name: Build and test with Maven
        run: mvn clean verify